### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gnardin** [roborescue/rcrs-server#8]
Cloning the RCRS-Server repository and running the commands
`ant clean`
`ant`
generates the following error

> BUILD FAILED
> /home/gnardin/rcrs-server/build-javadoc.xml:5: javax.script.ScriptException: ReferenceError: "importClass" is not defined in <eval> at line number 3
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
> 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.tools.ant.util.ReflectUtil.invoke(ReflectUtil.java:109)
> 	at org.apache.tools.ant.util.ReflectWrapper.invoke(ReflectWrapper.java:81)
> 	at org.apache.tools.ant.util.optional.JavaxScriptRunner.evaluateScript(JavaxScriptRunner.java:103)
> 	at org.apache.tools.ant.util.optional.JavaxScriptRunner.executeScript(JavaxScriptRunner.java:67)
> 	at org.apache.tools.ant.taskdefs.optional.Script.execute(Script.java:53)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
> 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> 	at org.apache.tools.ant.Task.perform(Task.java:348)
> 	at org.apache.tools.ant.Target.execute(Target.java:435)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
> 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
> 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
> 	at org.apache.tools.ant.Main.runBuild(Main.java:854)
> 	at org.apache.tools.ant.Main.startAnt(Main.java:236)
> 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
> 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
> Caused by: <eval>:3 ReferenceError: "importClass" is not defined
> 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
> 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
> 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
> 	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
> 	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:3)
> 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
> 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
> 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
> 	... 29 more
> 
> Total time: 6 seconds

_

**Comment by gnardin** [comment]
The error was caused because of Ant and Java 8 Javascript Engine backwards compatibility. The solution was to include the line of code 
```load('nashorn:mozilla_compat.js')```
before the ```importClass``` instruction inside the ```<script language="javascript">``` in the files
```
build-checjkstyle.xml
build-findbugs.xml
build-javadoc.xml
build-junit.xml
```
